### ISSUE TITLE
Question about training on EM noise 

### ISSUE THREAD

**Issue by butybone** [fshp971/robust-unlearnable-examples#2]
I'm generating error minimizing noise for cifar10 using :
python generate_em.py \
    --arch resnet18 \
    --dataset cifar10 \
    --train-steps 5000 \
    --batch-size 128 \
    --optim sgd \
    --lr 0.1 \
    --lr-decay-rate 0.1 \
    --lr-decay-freq 2000 \
    --weight-decay 5e-4 \
    --momentum 0.9 \
    --pgd-radius 8 \
    --pgd-steps 10 \
    --pgd-step-size 1.6 \
    --pgd-random-start \
    --report-freq 1000 \
    --save-freq 1000 \
    --data-dir ./data \
    --save-dir ./exp_data/cifar10/noise/em8 \
    --save-name em
_____________________________________________________________________

And perform standard training on error minimizing noise poisoned dataset using:
python train.py \
    --arch resnet18 \
    --dataset cifar10 \
    --train-steps 40000 \
    --batch-size 128 \
    --optim sgd \
    --lr 0.1 \
    --lr-decay-rate 0.1 \
    --lr-decay-freq 16000 \
    --weight-decay 5e-4 \
    --momentum 0.9 \
    --pgd-radius 0 \
    --pgd-steps 10 \
    --pgd-step-size 0.8 \
    --pgd-random-start \
    --report-freq 1000 \
    --save-freq 100000 \
    --noise-path ./exp_data/cifar10/noise/em8/em-fin-def-noise.pkl \
    --data-dir ./data \
    --save-dir ./exp_data/cifar10/train/em8/em \
    --save-name train
_____________________________________________________________________

And the trained model accuarcy on clean testset is about 10.10± which is far below the result in your paper (13.20 in Table 1, 16.84 in Table 7 ).  I'm quite confused by this huge difference. If I set the parameters wrong or it's due to the randomness of the experiments?

**Comment by fshp971** [comment]
Hi,

The parameters you set are correct. I guess the difference between your EM result on CIFAR-10 and mine is due to the randomness of the experiment.

However, I do not think such a difference is huge. Actually, both your result (10.10%) and mine (13.20%) are close to the accuracy of random-guessing on CIFAR-10 (10%).

Best,

**Comment by butybone** [comment]
Thanks!
