### ISSUE TITLE
Hi! Can you share the REM examples for imagenet100?

### ISSUE THREAD

**Issue by lyumingzhi** [fshp971/robust-unlearnable-examples#3]
Thank you very much for your great work! Would you mind sharing REM examples for imagenet100 by gdrive or email? I believe it is more common used for most of the cases.

**Comment by fshp971** [comment]
Hi,

Currently I would not share the noises for imagenet due to its large file size.

If you need partial results for CIFAR-10/CIFAR-100, please send me a request email.
