### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by Weixiang-Sun** [fshp971/robust-unlearnable-examples#5]
Hi,
After i get the noise.pkl file, how should i get the correct visulization result?
I tried noise*255,but it seems it;s wrong

**Comment by fshp971** [comment]
Hi,
For a noise that is generated with adversarial perturbation radius $\epsilon_a$, you should normalize it to $(\mathrm{noise} + \epsilon_a) \cdot \frac{255}{2 \epsilon_a}$ to get the visualization result.

**Comment by Weixiang-Sun** [comment]
Hi, if I don't normalize the data, is there any different of visualization or different effectiveness of the noise?

**Comment by fshp971** [comment]
Hi,

The purpose of normalization is to rescale the noise to fit the range [0,
255], which is the pixel range of 8-bit RGB images.
You can try not normalizing the noise, but the visualization result might
not be good.

Best,
Shaopeng
--------
Web: https://shaopengfu.me
